@echo off
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSKmu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSKmu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSumu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSumu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSOmu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSOmu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSymu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSymu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS2mu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS2mu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTVOmu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTVOmu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTUGmu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTUGmu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSCmu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSCmu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSGmu1aB.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSGmu1aB.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2' -OutFile 'memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLDz8Z1JlFc-K.woff2' -OutFile 'pxiByp8kv8JHgFVrLDz8Z1JlFc-K.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLDz8Z1xlFQ.woff2' -OutFile 'pxiByp8kv8JHgFVrLDz8Z1xlFQ.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiEyp8kv8JHgFVrJJnecmNE.woff2' -OutFile 'pxiEyp8kv8JHgFVrJJnecmNE.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiEyp8kv8JHgFVrJJfecg.woff2' -OutFile 'pxiEyp8kv8JHgFVrJJfecg.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLGT9Z1JlFc-K.woff2' -OutFile 'pxiByp8kv8JHgFVrLGT9Z1JlFc-K.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLGT9Z1xlFQ.woff2' -OutFile 'pxiByp8kv8JHgFVrLGT9Z1xlFQ.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLEj6Z1JlFc-K.woff2' -OutFile 'pxiByp8kv8JHgFVrLEj6Z1JlFc-K.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLEj6Z1xlFQ.woff2' -OutFile 'pxiByp8kv8JHgFVrLEj6Z1xlFQ.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLCz7Z1JlFc-K.woff2' -OutFile 'pxiByp8kv8JHgFVrLCz7Z1JlFc-K.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2' -OutFile 'pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2'"
powershell -Command "Invoke-WebRequest -Uri 'https://fonts.gstatic.com/s/fredokaone/v14/k3kUo8kEI-tA1RRcTZGmTlHGCac.woff2' -OutFile 'k3kUo8kEI-tA1RRcTZGmTlHGCac.woff2'"

pause
