export const _COMUNAS_ = [
    { id_comuna: 1101, nombre: 'Iquique', id_region: 1 },
    { id_comuna: 1107, nombre: 'Alto Hospicio', id_region: 1 },
    { id_comuna: 1401, nombre: 'Pozo Almonte', id_region: 1 },
    { id_comuna: 1402, nombre: 'Camiña', id_region: 1 },
    { id_comuna: 1403, nombre: 'Colchane', id_region: 1 },
    { id_comuna: 1404, nombre: 'Huara', id_region: 1 },
    { id_comuna: 1405, nombre: 'Pica', id_region: 1 },
    { id_comuna: 2101, nombre: 'Antofagasta', id_region: 2 },
    { id_comuna: 2102, nombre: 'Mejillones', id_region: 2 },
    { id_comuna: 2103, nombre: 'Sierra Gorda', id_region: 2 },
    { id_comuna: 2104, nombre: 'Taltal', id_region: 2 },
    { id_comuna: 2201, nombre: 'Calama', id_region: 2 },
    { id_comuna: 2202, nombre: 'Ollagüe', id_region: 2 },
    { id_comuna: 2203, nombre: 'San Pedro de Atacama', id_region: 2 },
    { id_comuna: 2301, nombre: 'Tocopilla', id_region: 2 },
    { id_comuna: 2302, nombre: 'María Elena', id_region: 2 },
    { id_comuna: 3101, nombre: 'Copiapó', id_region: 3 },
    { id_comuna: 3102, nombre: 'Caldera', id_region: 3 },
    { id_comuna: 3103, nombre: 'Tierra Amarilla', id_region: 3 },
    { id_comuna: 3201, nombre: 'Chañaral', id_region: 3 },
    { id_comuna: 3202, nombre: 'Diego de Almagro', id_region: 3 },
    { id_comuna: 3301, nombre: 'Vallenar', id_region: 3 },
    { id_comuna: 3302, nombre: 'Alto del Carmen', id_region: 3 },
    { id_comuna: 3303, nombre: 'Freirina', id_region: 3 },
    { id_comuna: 3304, nombre: 'Huasco', id_region: 3 },
    { id_comuna: 4101, nombre: 'La Serena', id_region: 4 },
    { id_comuna: 4102, nombre: 'Coquimbo', id_region: 4 },
    { id_comuna: 4103, nombre: 'Andacollo', id_region: 4 },
    { id_comuna: 4104, nombre: 'La Higuera', id_region: 4 },
    { id_comuna: 4105, nombre: 'Paiguano', id_region: 4 },
    { id_comuna: 4106, nombre: 'Vicuña', id_region: 4 },
    { id_comuna: 4201, nombre: 'Illapel', id_region: 4 },
    { id_comuna: 4202, nombre: 'Canela', id_region: 4 },
    { id_comuna: 4203, nombre: 'Los Vilos', id_region: 4 },
    { id_comuna: 4204, nombre: 'Salamanca', id_region: 4 },
    { id_comuna: 4301, nombre: 'Ovalle', id_region: 4 },
    { id_comuna: 4302, nombre: 'Combarbalá', id_region: 4 },
    { id_comuna: 4303, nombre: 'Monte Patria', id_region: 4 },
    { id_comuna: 4304, nombre: 'Punitaqui', id_region: 4 },
    { id_comuna: 4305, nombre: 'Río Hurtado', id_region: 4 },
    { id_comuna: 5101, nombre: 'Valparaíso', id_region: 5 },
    { id_comuna: 5102, nombre: 'Casablanca', id_region: 5 },
    { id_comuna: 5103, nombre: 'Concón', id_region: 5 },
    { id_comuna: 5104, nombre: 'Juan Fernández', id_region: 5 },
    { id_comuna: 5105, nombre: 'Puchuncaví', id_region: 5 },
    { id_comuna: 5107, nombre: 'Quintero', id_region: 5 },
    { id_comuna: 5109, nombre: 'Viña del Mar', id_region: 5 },
    { id_comuna: 5201, nombre: 'Isla  de Pascua', id_region: 5 },
    { id_comuna: 5301, nombre: 'Los Andes', id_region: 5 },
    { id_comuna: 5302, nombre: 'Calle Larga', id_region: 5 },
    { id_comuna: 5303, nombre: 'Rinconada', id_region: 5 },
    { id_comuna: 5304, nombre: 'San Esteban', id_region: 5 },
    { id_comuna: 5401, nombre: 'La Ligua', id_region: 5 },
    { id_comuna: 5402, nombre: 'Cabildo', id_region: 5 },
    { id_comuna: 5403, nombre: 'Papudo', id_region: 5 },
    { id_comuna: 5404, nombre: 'Petorca', id_region: 5 },
    { id_comuna: 5405, nombre: 'Zapallar', id_region: 5 },
    { id_comuna: 5501, nombre: 'Quillota', id_region: 5 },
    { id_comuna: 5502, nombre: 'Calera', id_region: 5 },
    { id_comuna: 5503, nombre: 'Hijuelas', id_region: 5 },
    { id_comuna: 5504, nombre: 'La Cruz', id_region: 5 },
    { id_comuna: 5506, nombre: 'Nogales', id_region: 5 },
    { id_comuna: 5601, nombre: 'San Antonio', id_region: 5 },
    { id_comuna: 5602, nombre: 'Algarrobo', id_region: 5 },
    { id_comuna: 5603, nombre: 'Cartagena', id_region: 5 },
    { id_comuna: 5604, nombre: 'El Quisco', id_region: 5 },
    { id_comuna: 5605, nombre: 'El Tabo', id_region: 5 },
    { id_comuna: 5606, nombre: 'Santo Domingo', id_region: 5 },
    { id_comuna: 5701, nombre: 'San Felipe', id_region: 5 },
    { id_comuna: 5702, nombre: 'Catemu', id_region: 5 },
    { id_comuna: 5703, nombre: 'Llaillay', id_region: 5 },
    { id_comuna: 5704, nombre: 'Panquehue', id_region: 5 },
    { id_comuna: 5705, nombre: 'Putaendo', id_region: 5 },
    { id_comuna: 5706, nombre: 'Santa María', id_region: 5 },
    { id_comuna: 5801, nombre: 'Quilpué', id_region: 5 },
    { id_comuna: 5802, nombre: 'Limache', id_region: 5 },
    { id_comuna: 5803, nombre: 'Olmué', id_region: 5 },
    { id_comuna: 5804, nombre: 'Villa Alemana', id_region: 5 },
    { id_comuna: 6101, nombre: 'Rancagua', id_region: 6 },
    { id_comuna: 6102, nombre: 'Codegua', id_region: 6 },
    { id_comuna: 6103, nombre: 'Coinco', id_region: 6 },
    { id_comuna: 6104, nombre: 'Coltauco', id_region: 6 },
    { id_comuna: 6105, nombre: 'Doñihue', id_region: 6 },
    { id_comuna: 6106, nombre: 'Graneros', id_region: 6 },
    { id_comuna: 6107, nombre: 'Las Cabras', id_region: 6 },
    { id_comuna: 6108, nombre: 'Machalí', id_region: 6 },
    { id_comuna: 6109, nombre: 'Malloa', id_region: 6 },
    { id_comuna: 6110, nombre: 'Mostazal', id_region: 6 },
    { id_comuna: 6111, nombre: 'Olivar', id_region: 6 },
    { id_comuna: 6112, nombre: 'Peumo', id_region: 6 },
    { id_comuna: 6113, nombre: 'Pichidegua', id_region: 6 },
    { id_comuna: 6114, nombre: 'Quinta de Tilcoco', id_region: 6 },
    { id_comuna: 6115, nombre: 'Rengo', id_region: 6 },
    { id_comuna: 6116, nombre: 'Requínoa', id_region: 6 },
    { id_comuna: 6117, nombre: 'San Vicente', id_region: 6 },
    { id_comuna: 6201, nombre: 'Pichilemu', id_region: 6 },
    { id_comuna: 6202, nombre: 'La Estrella', id_region: 6 },
    { id_comuna: 6203, nombre: 'Litueche', id_region: 6 },
    { id_comuna: 6204, nombre: 'Marchihue', id_region: 6 },
    { id_comuna: 6205, nombre: 'Navidad', id_region: 6 },
    { id_comuna: 6206, nombre: 'Paredones', id_region: 6 },
    { id_comuna: 6301, nombre: 'San Fernando', id_region: 6 },
    { id_comuna: 6302, nombre: 'Chépica', id_region: 6 },
    { id_comuna: 6303, nombre: 'Chimbarongo', id_region: 6 },
    { id_comuna: 6304, nombre: 'Lolol', id_region: 6 },
    { id_comuna: 6305, nombre: 'Nancagua', id_region: 6 },
    { id_comuna: 6306, nombre: 'Palmilla', id_region: 6 },
    { id_comuna: 6307, nombre: 'Peralillo', id_region: 6 },
    { id_comuna: 6308, nombre: 'Placilla', id_region: 6 },
    { id_comuna: 6309, nombre: 'Pumanque', id_region: 6 },
    { id_comuna: 6310, nombre: 'Santa Cruz', id_region: 6 },
    { id_comuna: 7101, nombre: 'Talca', id_region: 7 },
    { id_comuna: 7102, nombre: 'Constitución', id_region: 7 },
    { id_comuna: 7103, nombre: 'Curepto', id_region: 7 },
    { id_comuna: 7104, nombre: 'Empedrado', id_region: 7 },
    { id_comuna: 7105, nombre: 'Maule', id_region: 7 },
    { id_comuna: 7106, nombre: 'Pelarco', id_region: 7 },
    { id_comuna: 7107, nombre: 'Pencahue', id_region: 7 },
    { id_comuna: 7108, nombre: 'Río Claro', id_region: 7 },
    { id_comuna: 7109, nombre: 'San Clemente', id_region: 7 },
    { id_comuna: 7110, nombre: 'San Rafael', id_region: 7 },
    { id_comuna: 7201, nombre: 'Cauquenes', id_region: 7 },
    { id_comuna: 7202, nombre: 'Chanco', id_region: 7 },
    { id_comuna: 7203, nombre: 'Pelluhue', id_region: 7 },
    { id_comuna: 7301, nombre: 'Curicó', id_region: 7 },
    { id_comuna: 7302, nombre: 'Hualañé', id_region: 7 },
    { id_comuna: 7303, nombre: 'Licantén', id_region: 7 },
    { id_comuna: 7304, nombre: 'Molina', id_region: 7 },
    { id_comuna: 7305, nombre: 'Rauco', id_region: 7 },
    { id_comuna: 7306, nombre: 'Romeral', id_region: 7 },
    { id_comuna: 7307, nombre: 'Sagrada Familia', id_region: 7 },
    { id_comuna: 7308, nombre: 'Teno', id_region: 7 },
    { id_comuna: 7309, nombre: 'Vichuquén', id_region: 7 },
    { id_comuna: 7401, nombre: 'Linares', id_region: 7 },
    { id_comuna: 7402, nombre: 'Colbún', id_region: 7 },
    { id_comuna: 7403, nombre: 'Longaví', id_region: 7 },
    { id_comuna: 7404, nombre: 'Parral', id_region: 7 },
    { id_comuna: 7405, nombre: 'Retiro', id_region: 7 },
    { id_comuna: 7406, nombre: 'San Javier', id_region: 7 },
    { id_comuna: 7407, nombre: 'Villa Alegre', id_region: 7 },
    { id_comuna: 7408, nombre: 'Yerbas Buenas', id_region: 7 },
    { id_comuna: 8101, nombre: 'Concepción', id_region: 8 },
    { id_comuna: 8102, nombre: 'Coronel', id_region: 8 },
    { id_comuna: 8103, nombre: 'Chiguayante', id_region: 8 },
    { id_comuna: 8104, nombre: 'Florida', id_region: 8 },
    { id_comuna: 8105, nombre: 'Hualqui', id_region: 8 },
    { id_comuna: 8106, nombre: 'Lota', id_region: 8 },
    { id_comuna: 8107, nombre: 'Penco', id_region: 8 },
    { id_comuna: 8108, nombre: 'San Pedro de la Paz', id_region: 8 },
    { id_comuna: 8109, nombre: 'Santa Juana', id_region: 8 },
    { id_comuna: 8110, nombre: 'Talcahuano', id_region: 8 },
    { id_comuna: 8111, nombre: 'Tomé', id_region: 8 },
    { id_comuna: 8112, nombre: 'Hualpén', id_region: 8 },
    { id_comuna: 8201, nombre: 'Lebu', id_region: 8 },
    { id_comuna: 8202, nombre: 'Arauco', id_region: 8 },
    { id_comuna: 8203, nombre: 'Cañete', id_region: 8 },
    { id_comuna: 8204, nombre: 'Contulmo', id_region: 8 },
    { id_comuna: 8205, nombre: 'Curanilahue', id_region: 8 },
    { id_comuna: 8206, nombre: 'Los Álamos', id_region: 8 },
    { id_comuna: 8207, nombre: 'Tirúa', id_region: 8 },
    { id_comuna: 8301, nombre: 'Los Ángeles', id_region: 8 },
    { id_comuna: 8302, nombre: 'Antuco', id_region: 8 },
    { id_comuna: 8303, nombre: 'Cabrero', id_region: 8 },
    { id_comuna: 8304, nombre: 'Laja', id_region: 8 },
    { id_comuna: 8305, nombre: 'Mulchén', id_region: 8 },
    { id_comuna: 8306, nombre: 'Nacimiento', id_region: 8 },
    { id_comuna: 8307, nombre: 'Negrete', id_region: 8 },
    { id_comuna: 8308, nombre: 'Quilaco', id_region: 8 },
    { id_comuna: 8309, nombre: 'Quilleco', id_region: 8 },
    { id_comuna: 8310, nombre: 'San Rosendo', id_region: 8 },
    { id_comuna: 8311, nombre: 'Santa Bárbara', id_region: 8 },
    { id_comuna: 8312, nombre: 'Tucapel', id_region: 8 },
    { id_comuna: 8313, nombre: 'Yumbel', id_region: 8 },
    { id_comuna: 8314, nombre: 'Alto Biobío', id_region: 8 },
    { id_comuna: 9101, nombre: 'Temuco', id_region: 9 },
    { id_comuna: 9102, nombre: 'Carahue', id_region: 9 },
    { id_comuna: 9103, nombre: 'Cunco', id_region: 9 },
    { id_comuna: 9104, nombre: 'Curarrehue', id_region: 9 },
    { id_comuna: 9105, nombre: 'Freire', id_region: 9 },
    { id_comuna: 9106, nombre: 'Galvarino', id_region: 9 },
    { id_comuna: 9107, nombre: 'Gorbea', id_region: 9 },
    { id_comuna: 9108, nombre: 'Lautaro', id_region: 9 },
    { id_comuna: 9109, nombre: 'Loncoche', id_region: 9 },
    { id_comuna: 9110, nombre: 'Melipeuco', id_region: 9 },
    { id_comuna: 9111, nombre: 'Nueva Imperial', id_region: 9 },
    { id_comuna: 9112, nombre: 'Padre Las Casas', id_region: 9 },
    { id_comuna: 9113, nombre: 'Perquenco', id_region: 9 },
    { id_comuna: 9114, nombre: 'Pitrufquén', id_region: 9 },
    { id_comuna: 9115, nombre: 'Pucón', id_region: 9 },
    { id_comuna: 9116, nombre: 'Saavedra', id_region: 9 },
    { id_comuna: 9117, nombre: 'Teodoro Schmidt', id_region: 9 },
    { id_comuna: 9118, nombre: 'Toltén', id_region: 9 },
    { id_comuna: 9119, nombre: 'Vilcún', id_region: 9 },
    { id_comuna: 9120, nombre: 'Villarrica', id_region: 9 },
    { id_comuna: 9121, nombre: 'Cholchol', id_region: 9 },
    { id_comuna: 9201, nombre: 'Angol', id_region: 9 },
    { id_comuna: 9202, nombre: 'Collipulli', id_region: 9 },
    { id_comuna: 9203, nombre: 'Curacautín', id_region: 9 },
    { id_comuna: 9204, nombre: 'Ercilla', id_region: 9 },
    { id_comuna: 9205, nombre: 'Lonquimay', id_region: 9 },
    { id_comuna: 9206, nombre: 'Los Sauces', id_region: 9 },
    { id_comuna: 9207, nombre: 'Lumaco', id_region: 9 },
    { id_comuna: 9208, nombre: 'Purén', id_region: 9 },
    { id_comuna: 9209, nombre: 'Renaico', id_region: 9 },
    { id_comuna: 9210, nombre: 'Traiguén', id_region: 9 },
    { id_comuna: 9211, nombre: 'Victoria', id_region: 9 },
    { id_comuna: 10101, nombre: 'Puerto Montt', id_region: 10 },
    { id_comuna: 10102, nombre: 'Calbuco', id_region: 10 },
    { id_comuna: 10103, nombre: 'Cochamó', id_region: 10 },
    { id_comuna: 10104, nombre: 'Fresia', id_region: 10 },
    { id_comuna: 10105, nombre: 'Frutillar', id_region: 10 },
    { id_comuna: 10106, nombre: 'Los Muermos', id_region: 10 },
    { id_comuna: 10107, nombre: 'Llanquihue', id_region: 10 },
    { id_comuna: 10108, nombre: 'Maullín', id_region: 10 },
    { id_comuna: 10109, nombre: 'Puerto Varas', id_region: 10 },
    { id_comuna: 10201, nombre: 'Castro', id_region: 10 },
    { id_comuna: 10202, nombre: 'Ancud', id_region: 10 },
    { id_comuna: 10203, nombre: 'Chonchi', id_region: 10 },
    { id_comuna: 10204, nombre: 'Curaco de Vélez', id_region: 10 },
    { id_comuna: 10205, nombre: 'Dalcahue', id_region: 10 },
    { id_comuna: 10206, nombre: 'Puqueldón', id_region: 10 },
    { id_comuna: 10207, nombre: 'Queilén', id_region: 10 },
    { id_comuna: 10208, nombre: 'Quellón', id_region: 10 },
    { id_comuna: 10209, nombre: 'Quemchi', id_region: 10 },
    { id_comuna: 10210, nombre: 'Quinchao', id_region: 10 },
    { id_comuna: 10301, nombre: 'Osorno', id_region: 10 },
    { id_comuna: 10302, nombre: 'Puerto Octay', id_region: 10 },
    { id_comuna: 10303, nombre: 'Purranque', id_region: 10 },
    { id_comuna: 10304, nombre: 'Puyehue', id_region: 10 },
    { id_comuna: 10305, nombre: 'Río Negro', id_region: 10 },
    { id_comuna: 10306, nombre: 'San Juan de la Costa', id_region: 10 },
    { id_comuna: 10307, nombre: 'San Pablo', id_region: 10 },
    { id_comuna: 10401, nombre: 'Chaitén', id_region: 10 },
    { id_comuna: 10402, nombre: 'Futaleufú', id_region: 10 },
    { id_comuna: 10403, nombre: 'Hualaihué', id_region: 10 },
    { id_comuna: 10404, nombre: 'Palena', id_region: 10 },
    { id_comuna: 11101, nombre: 'Coihaique', id_region: 11 },
    { id_comuna: 11102, nombre: 'Lago Verde', id_region: 11 },
    { id_comuna: 11201, nombre: 'Aisén', id_region: 11 },
    { id_comuna: 11202, nombre: 'Cisnes', id_region: 11 },
    { id_comuna: 11203, nombre: 'Guaitecas', id_region: 11 },
    { id_comuna: 11301, nombre: 'Cochrane', id_region: 11 },
    { id_comuna: 11302, nombre: "O'Higgins", id_region: 11 },
    { id_comuna: 11303, nombre: 'Tortel', id_region: 11 },
    { id_comuna: 11401, nombre: 'Chile Chico', id_region: 11 },
    { id_comuna: 11402, nombre: 'Río Ibáñez', id_region: 11 },
    { id_comuna: 12101, nombre: 'Punta Arenas', id_region: 12 },
    { id_comuna: 12102, nombre: 'Laguna Blanca', id_region: 12 },
    { id_comuna: 12103, nombre: 'Río Verde', id_region: 12 },
    { id_comuna: 12104, nombre: 'San Gregorio', id_region: 12 },
    { id_comuna: 12201, nombre: 'Cabo de Hornos', id_region: 12 },
    { id_comuna: 12202, nombre: 'Antártica', id_region: 12 },
    { id_comuna: 12301, nombre: 'Porvenir', id_region: 12 },
    { id_comuna: 12302, nombre: 'Primavera', id_region: 12 },
    { id_comuna: 12303, nombre: 'Timaukel', id_region: 12 },
    { id_comuna: 12401, nombre: 'Natales', id_region: 12 },
    { id_comuna: 12402, nombre: 'Torres del Paine', id_region: 12 },
    { id_comuna: 13101, nombre: 'Santiago', id_region: 13 },
    { id_comuna: 13102, nombre: 'Cerrillos', id_region: 13 },
    { id_comuna: 13103, nombre: 'Cerro Navia', id_region: 13 },
    { id_comuna: 13104, nombre: 'Conchalí', id_region: 13 },
    { id_comuna: 13105, nombre: 'El Bosque', id_region: 13 },
    { id_comuna: 13106, nombre: 'Estación Central', id_region: 13 },
    { id_comuna: 13107, nombre: 'Huechuraba', id_region: 13 },
    { id_comuna: 13108, nombre: 'Independencia', id_region: 13 },
    { id_comuna: 13109, nombre: 'La Cisterna', id_region: 13 },
    { id_comuna: 13110, nombre: 'La Florida', id_region: 13 },
    { id_comuna: 13111, nombre: 'La Granja', id_region: 13 },
    { id_comuna: 13112, nombre: 'La Pintana', id_region: 13 },
    { id_comuna: 13113, nombre: 'La Reina', id_region: 13 },
    { id_comuna: 13114, nombre: 'Las Condes', id_region: 13 },
    { id_comuna: 13115, nombre: 'Lo Barnechea', id_region: 13 },
    { id_comuna: 13116, nombre: 'Lo Espejo', id_region: 13 },
    { id_comuna: 13117, nombre: 'Lo Prado', id_region: 13 },
    { id_comuna: 13118, nombre: 'Macul', id_region: 13 },
    { id_comuna: 13119, nombre: 'Maipú', id_region: 13 },
    { id_comuna: 13120, nombre: 'Ñuñoa', id_region: 13 },
    { id_comuna: 13121, nombre: 'Pedro Aguirre Cerda', id_region: 13 },
    { id_comuna: 13122, nombre: 'Peñalolén', id_region: 13 },
    { id_comuna: 13123, nombre: 'Providencia', id_region: 13 },
    { id_comuna: 13124, nombre: 'Pudahuel', id_region: 13 },
    { id_comuna: 13125, nombre: 'Quilicura', id_region: 13 },
    { id_comuna: 13126, nombre: 'Quinta Normal', id_region: 13 },
    { id_comuna: 13127, nombre: 'Recoleta', id_region: 13 },
    { id_comuna: 13128, nombre: 'Renca', id_region: 13 },
    { id_comuna: 13129, nombre: 'San Joaquín', id_region: 13 },
    { id_comuna: 13130, nombre: 'San Miguel', id_region: 13 },
    { id_comuna: 13131, nombre: 'San Ramón', id_region: 13 },
    { id_comuna: 13132, nombre: 'Vitacura', id_region: 13 },
    { id_comuna: 13201, nombre: 'Puente Alto', id_region: 13 },
    { id_comuna: 13202, nombre: 'Pirque', id_region: 13 },
    { id_comuna: 13203, nombre: 'San José de Maipo', id_region: 13 },
    { id_comuna: 13301, nombre: 'Colina', id_region: 13 },
    { id_comuna: 13302, nombre: 'Lampa', id_region: 13 },
    { id_comuna: 13303, nombre: 'Tiltil', id_region: 13 },
    { id_comuna: 13401, nombre: 'San Bernardo', id_region: 13 },
    { id_comuna: 13402, nombre: 'Buin', id_region: 13 },
    { id_comuna: 13403, nombre: 'Calera de Tango', id_region: 13 },
    { id_comuna: 13404, nombre: 'Paine', id_region: 13 },
    { id_comuna: 13501, nombre: 'Melipilla', id_region: 13 },
    { id_comuna: 13502, nombre: 'Alhué', id_region: 13 },
    { id_comuna: 13503, nombre: 'Curacaví', id_region: 13 },
    { id_comuna: 13504, nombre: 'María Pinto', id_region: 13 },
    { id_comuna: 13505, nombre: 'San Pedro', id_region: 13 },
    { id_comuna: 13601, nombre: 'Talagante', id_region: 13 },
    { id_comuna: 13602, nombre: 'El Monte', id_region: 13 },
    { id_comuna: 13603, nombre: 'Isla de Maipo', id_region: 13 },
    { id_comuna: 13604, nombre: 'Padre Hurtado', id_region: 13 },
    { id_comuna: 13605, nombre: 'Peñaflor', id_region: 13 },
    { id_comuna: 14101, nombre: 'Valdivia', id_region: 14 },
    { id_comuna: 14102, nombre: 'Corral', id_region: 14 },
    { id_comuna: 14103, nombre: 'Lanco', id_region: 14 },
    { id_comuna: 14104, nombre: 'Los Lagos', id_region: 14 },
    { id_comuna: 14105, nombre: 'Máfil', id_region: 14 },
    { id_comuna: 14106, nombre: 'Mariquina', id_region: 14 },
    { id_comuna: 14107, nombre: 'Paillaco', id_region: 14 },
    { id_comuna: 14108, nombre: 'Panguipulli', id_region: 14 },
    { id_comuna: 14201, nombre: 'La Unión', id_region: 14 },
    { id_comuna: 14202, nombre: 'Futrono', id_region: 14 },
    { id_comuna: 14203, nombre: 'Lago Ranco', id_region: 14 },
    { id_comuna: 14204, nombre: 'Río Bueno', id_region: 14 },
    { id_comuna: 15101, nombre: 'Arica', id_region: 15 },
    { id_comuna: 15102, nombre: 'Camarones', id_region: 15 },
    { id_comuna: 15201, nombre: 'Putre', id_region: 15 },
    { id_comuna: 15202, nombre: 'General Lagos', id_region: 15 },
    { id_comuna: 16101, nombre: 'Chillán', id_region: 16 },
    { id_comuna: 16102, nombre: 'Bulnes', id_region: 16 },
    { id_comuna: 16103, nombre: 'Chillán Viejo', id_region: 16 },
    { id_comuna: 16104, nombre: 'El Carmen', id_region: 16 },
    { id_comuna: 16105, nombre: 'Pemuco', id_region: 16 },
    { id_comuna: 16106, nombre: 'Pinto', id_region: 16 },
    { id_comuna: 16107, nombre: 'Quillón', id_region: 16 },
    { id_comuna: 16108, nombre: 'San Ignacio', id_region: 16 },
    { id_comuna: 16109, nombre: 'Yungay', id_region: 16 },
    { id_comuna: 16201, nombre: 'Quirihue', id_region: 16 },
    { id_comuna: 16202, nombre: 'Cobquecura', id_region: 16 },
    { id_comuna: 16203, nombre: 'Coelemu', id_region: 16 },
    { id_comuna: 16204, nombre: 'Ninhue', id_region: 16 },
    { id_comuna: 16205, nombre: 'Portezuelo', id_region: 16 },
    { id_comuna: 16206, nombre: 'Ránquil', id_region: 16 },
    { id_comuna: 16207, nombre: 'Treguaco', id_region: 16 },
    { id_comuna: 16301, nombre: 'San Carlos', id_region: 16 },
    { id_comuna: 16302, nombre: 'Coihueco', id_region: 16 },
    { id_comuna: 16303, nombre: 'Ñiquén', id_region: 16 },
    { id_comuna: 16304, nombre: 'San Fabián', id_region: 16 },
    { id_comuna: 16305, nombre: 'San Nicolás', id_region: 16 },
  ]